Pin 'mistune' to last known good version (#70)
This change fixes the error:

    Module 'mistune' has no attribute 'BlockGrammar'

The mistune module is used by m2r2, but the version was not specified
tightly, so the release of mistune 2.0 caused a breakage due to
interface changes.

[ROCm/hipSOLVER commit: c96aa1ef333eeda14d4fd454483c9967ec118087]